### PR TITLE
locking: Prevent deadlock by making lock ordering consistent.

### PR DESCRIPTION
**Pull request by ksedgwic**
I reordered lock acquisition to always be hm first, then gm and finally cm.

Fixes observed deadlock.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Just curious, did you try with https://github.com/sasha-s/go-deadlock?

**Comment by tschottdorf** [comment]
LGTM (but I'm just randomly here and have no power).

**Comment by ksedgwic** [comment]
> Just curious, did you try with https://github.com/sasha-s/go-deadlock?

No, we figured it out by looking at a goroutine dump from the deadlocked process.

The [go-deadlock](https://github.com/sasha-s/go-deadlock) project looks cool, thanks for pointing it out!

**Comment by codahale** [comment]
Thanks for the diagnosis and fix, @ksedgwic!

**Pull request merged**
